directive @goModel(
	model: String
	models: [String!]
) on OBJECT | INPUT_OBJECT | SCALAR | ENUM | INTERFACE | UNION

directive @goField(
	forceResolver: Boolean
	name: String
	omittable: Boolean
	type: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

directive @auth on FIELD_DEFINITION

input CartItemInput {
  itemID: ID!
  quantity: Int!
}

type Seller @goModel(model: "github.com/Hoher2000/shopQL/customModels.Seller") {
  id: ID!
  name: String!
  deals: Int!
  items(limit: Int = 3, offset: Int = 0): [Item!]! @goField(forceResolver: true)
}

type Item @goModel(model: "github.com/Hoher2000/shopQL/customModels.Item") {
  id: ID!
  name: String!
  inStockText: String! @goField(forceResolver: true)
  inCart: Int! @goField(forceResolver: true) @auth
  seller: Seller! @goField(forceResolver: true)
  catalog: Catalog! @goField(forceResolver: true)
  parent: Catalog! @goField(forceResolver: true)
  price: Int!
}

type Catalog @goModel(model: "github.com/Hoher2000/shopQL/customModels.Catalog") {
  id: ID!
  name: String!
  childs: [Catalog!]! @goField(forceResolver: true)
  parent: Catalog @goField(forceResolver: true)
  items(limit: Int = 3, offset: Int = 0): [Item!]! @goField(forceResolver: true) 
}

type OrderItem @goModel(model: "github.com/Hoher2000/shopQL/customModels.OrderItem") {
  item: Item! @goField(forceResolver: true)
  quantity: Int!
}

type Cart @goModel(model: "github.com/Hoher2000/shopQL/customModels.Cart") {
   items: [OrderItem!]! 
   count: Int! @goField(forceResolver: true)
   cost: Int! @goField(forceResolver: true)
}

type Query {
  Catalog(ID: ID!): Catalog 
  Seller(ID: ID!): Seller!
  MyCart: Cart! @auth
}

type Mutation {
  AddToCart(in: CartItemInput!): Cart! @auth
  RemoveFromCart(in: CartItemInput!): Cart! @auth
}
