// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CartItemInput struct {
	ItemID   string `json:"itemID"`
	Quantity int    `json:"quantity"`
}

type Mutation struct {
}

type Query struct {
}
